# Generated by Django 5.1.7 on 2025-05-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelTable(
            name="device",
            table=None,
        ),
        migrations.AlterModelTable(
            name="order",
            table=None,
        ),
        migrations.AlterModelTable(
            name="ordercommission",
            table=None,
        ),
        migrations.AlterModelTable(
            name="orderitem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="quotation",
            table=None,
        ),
        migrations.AlterModelTable(
            name="quotationitem",
            table=None,
        ),
    ]
