# Generated by Django 5.1.7 on 2025-05-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customer",
            table=None,
        ),
    ]
