version: '3.8'

services:
  db:
    image: mariadb:10.6
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME:-smarteq_dev}
      - MYSQL_USER=${DB_USER:-smarteq}
      - MYSQL_PASSWORD=${DB_PASSWORD:-smarteq}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
    restart: unless-stopped

volumes:
  mariadb_data: