# Generated by Django 5.1.7 on 2025-04-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="cost_price",
        ),
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Quantity"
            ),
        ),
    ]
