# Generated by Django 5.1.7 on 2025-04-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_item_cost_price_item_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Quantity"),
        ),
    ]
