# Generated by Django 5.1.7 on 2025-05-02 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_item_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="billofmaterials",
            name="alternative_group",
            field=models.CharField(
                blank=True,
                help_text="Group identifier for alternative components",
                max_length=50,
                null=True,
                verbose_name="Alternative Group",
            ),
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="is_default",
            field=models.BooleanField(
                default=True,
                help_text="Is this the default component to use",
                verbose_name="Default Component",
            ),
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="is_optional",
            field=models.BooleanField(
                default=False,
                help_text="Can this component be omitted or substituted",
                verbose_name="Optional Component",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="dealer_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Dealer Price"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="footprint",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Footprint"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="last_purchase_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Last Purchase Date"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="minimum_stock_level",
            field=models.IntegerField(default=0, verbose_name="Minimum Stock Level"),
        ),
        migrations.AddField(
            model_name="item",
            name="mpn",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Manufacturer Part Number",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="order_status",
            field=models.BooleanField(default=False, verbose_name="Order Status"),
        ),
        migrations.AddField(
            model_name="item",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Purchase Price",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Reference"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="sales_list_status",
            field=models.CharField(
                choices=[
                    ("NOT_LISTED", "Not Listed"),
                    ("CUSTOMER_LIST", "Customer Sales List"),
                    ("DEALER_LIST", "Dealer Sales List"),
                    ("BOTH_LISTS", "Both Sales Lists"),
                ],
                default="NOT_LISTED",
                max_length=20,
                verbose_name="Sales List Status",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="value",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Value"
            ),
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("SALE", "Sale"),
                            ("PRODUCTION_IN", "Production Input"),
                            ("PRODUCTION_OUT", "Production Output"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=20,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Positive for additions, negative for deductions",
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Transaction Date"
                    ),
                ),
                (
                    "reference_model",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Reference Model",
                    ),
                ),
                (
                    "reference_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Reference ID"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="inventory.item",
                        verbose_name="Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Transaction",
                "verbose_name_plural": "Inventory Transactions",
                "ordering": ["-transaction_date"],
                "abstract": False,
            },
        ),
    ]
