# Generated by Django 5.1.7 on 2025-05-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_billofmaterials_alternative_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="footprint",
        ),
        migrations.RemoveField(
            model_name="item",
            name="mpn",
        ),
        migrations.RemoveField(
            model_name="item",
            name="value",
        ),
    ]
