# Generated by Django 5.1.7 on 2025-05-02 19:06

import apps.inventory.models.excel_import
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_item_footprint_remove_item_mpn_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("RAW_MATERIALS", "Raw Materials"),
                            ("PRODUCTS", "Products"),
                            ("BOM", "Bill of Materials"),
                            ("ELECTRONIC_COMPONENTS", "Electronic Components"),
                        ],
                        max_length=30,
                        verbose_name="Import Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.inventory.models.excel_import.import_file_path,
                        verbose_name="Excel File",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "processed_count",
                    models.IntegerField(default=0, verbose_name="Processed Count"),
                ),
                (
                    "failed_count",
                    models.IntegerField(default=0, verbose_name="Failed Count"),
                ),
                (
                    "error_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Details"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="excel_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Processed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Excel Import",
                "verbose_name_plural": "Excel Imports",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("purchase_date", models.DateField(verbose_name="Purchase Date")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Quantity"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Price"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Supplier"
                    ),
                ),
                (
                    "invoice_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Invoice Reference",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_history",
                        to="inventory.item",
                        verbose_name="Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase History",
                "verbose_name_plural": "Purchase History",
                "ordering": ["-purchase_date"],
                "abstract": False,
            },
        ),
    ]
