# Generated by Django 5.1.7 on 2025-05-07 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_excelimport_purchasehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "output_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Actual quantity produced",
                        max_digits=10,
                        verbose_name="Output Quantity",
                    ),
                ),
                (
                    "execution_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Execution Date"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Executed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production",
                "verbose_name_plural": "Productions",
                "ordering": ["-execution_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("action", models.CharField(max_length=50, verbose_name="Action")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "previous_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Previous Data"
                    ),
                ),
                (
                    "new_data",
                    models.JSONField(blank=True, null=True, verbose_name="New Data"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_history_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="inventory.production",
                        verbose_name="Production",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production History",
                "verbose_name_plural": "Production History",
                "ordering": ["-timestamp"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "quantity_consumed",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="Quantity Consumed",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(max_length=50, verbose_name="Unit of Measure"),
                ),
                (
                    "input_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_consumptions",
                        to="inventory.item",
                        verbose_name="Input Item",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumed_items",
                        to="inventory.production",
                        verbose_name="Production",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Item",
                "verbose_name_plural": "Production Items",
                "ordering": ["production__execution_date", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Recipe Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "output_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        help_text="Amount produced per recipe execution",
                        max_digits=10,
                        verbose_name="Output Quantity",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(max_length=50, verbose_name="Unit of Measure"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "output_item",
                    models.ForeignKey(
                        help_text="The intermediate or final product being produced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="inventory.item",
                        verbose_name="Output Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="production",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productions",
                to="inventory.recipe",
                verbose_name="Recipe",
            ),
        ),
        migrations.CreateModel(
            name="RecipeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "quantity_required",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Amount of input item needed for one recipe execution",
                        max_digits=10,
                        verbose_name="Quantity Required",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(max_length=50, verbose_name="Unit of Measure"),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10,
                        help_text="Order of assembly/production",
                        verbose_name="Sequence",
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False,
                        help_text="Can this component be omitted",
                        verbose_name="Optional Component",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "input_item",
                    models.ForeignKey(
                        help_text="Component required for production",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_inputs",
                        to="inventory.item",
                        verbose_name="Input Item",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.recipe",
                        verbose_name="Recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Item",
                "verbose_name_plural": "Recipe Items",
                "ordering": ["recipe__name", "sequence"],
                "abstract": False,
                "unique_together": {("recipe", "input_item")},
            },
        ),
    ]
