# Generated by Django 5.1.7 on 2025-05-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0007_production_productionhistory_productionitem_recipe_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="BillOfMaterials",
        ),
    ]
