# Generated by Django 5.1.7 on 2025-05-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_delete_billofmaterials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="quantity",
            field=models.IntegerField(
                help_text="Positive for additions, negative for deductions",
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="processiteminput",
            name="quantity_consumed",
            field=models.IntegerField(verbose_name="Quantity Consumed"),
        ),
        migrations.AlterField(
            model_name="processitemoutput",
            name="quantity_produced",
            field=models.IntegerField(verbose_name="Quantity Produced"),
        ),
        migrations.AlterField(
            model_name="production",
            name="output_quantity",
            field=models.IntegerField(
                help_text="Actual quantity produced", verbose_name="Output Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="productionitem",
            name="quantity_consumed",
            field=models.IntegerField(verbose_name="Quantity Consumed"),
        ),
        migrations.AlterField(
            model_name="productionprocess",
            name="target_output_quantity",
            field=models.IntegerField(verbose_name="Target Output Quantity"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="output_quantity",
            field=models.IntegerField(
                default=1,
                help_text="Amount produced per recipe execution",
                verbose_name="Output Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="recipeitem",
            name="quantity_required",
            field=models.IntegerField(
                help_text="Amount of input item needed for one recipe execution",
                verbose_name="Quantity Required",
            ),
        ),
    ]
